CREATE TABLE IF NOT EXISTS`accounts` (
  id INT(255) UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  username VARCHAR(15) UNIQUE KEY NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(50) UNIQUE KEY NULL
  reg_date DATE NULL DEFAULT NULL,
  last_visit DATE NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `datos`(
  id INT(255) UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  owner_id INT(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NULL DEFAULT NULL,
  uri_id VARCHAR(50) NOT NULL,
  hash_id VARCHAR(255) UNIQUE KEY NOT NULL
);

ALTER TABLE `datos` ADD INDEX(`owner_id`);

CREATE TABLE IF NOT EXISTS `datos_arch`(
  `datos_id` INT(255) UNSIGNED UNIQUE KEY NOT NULL,
  `owner_id` INT(255) UNSIGNED NOT NULL,
  `json_data`TEXT NOT NULL,
  INDEX (`owner_id`)
)